/**
 * The guarded preset's composition text.
 *
 * A preset is an entry list; `cordis:include` reads another composition file and
 * applies `patches` to the entries it read, and an `insert` patch carrying an `id`
 * pushes its rows into that group's child list. That makes "the shipped preset
 * plus one row" expressible without copying it — a harness update to the shipped
 * composition then flows through instead of being frozen.
 *
 * @module dsh-cache-guard/preset-file
 */

/**
 * Render the guarded preset.
 * @param input `{ baseFileUrl, engineSpecifier, mode, thresholdRatio }`;
 *   `thresholdRatio` is optional and configures the engine's own trigger.
 * @returns YAML text for `agent.cordis.yml`.
 */
export function guardedPresetText({ baseFileUrl, engineSpecifier, mode = 'manual', thresholdRatio }) {
  const lines = [
    '# dsh-cache-guard — generated by tools/install-profile.mjs; edit the patch below.',
    '#',
    '# This is the shipped composition plus the guard\'s engine row. The include reads',
    '# the shipped file at mount time, so updates to it apply here too; the patch inserts',
    '# the guard into the "compaction" group, where it must sit because that group isolates',
    '# the "compaction" and "toolResultPruner" services from the rest of the preset.',
    '- id: base',
    "  name: 'cordis:include'",
    '  config:',
    `    path: '${baseFileUrl}'`,
    '    patches:',
    '      - id: compaction',
    '        insert:',
    '          - id: cache-guard',
    `            name: '${engineSpecifier}'`,
    '            config:',
    `              mode: ${mode}`,
  ]
  if (typeof thresholdRatio === 'number') {
    lines.push(
      '',
      '      # The engine\'s own trigger: compact once this share of the routed context',
      '      # window is in use. The shipped row carries no config, and a patch replaces a',
      '      # row\'s config rather than merging into it, so this is the whole of it.',
      '      - id: compaction-basic',
      '        config:',
      `          thresholdRatio: ${thresholdRatio}`,
    )
  }
  lines.push('')
  return lines.join('\n')
}
